config/routes.rb
Rails.application.routes.draw do
  root   'products#shop'
  resources :categories
  resources :products
  # get '/new_product'
  get '/detail_product/:id', to: 'products#detail'
  get '/shop/',    to: 'order_items#shopdetail'
  resources :users
  resources :order_items
  resources :orders
  resource :cart, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get    '/products',to: 'products#index'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'
   
  resources :users

  resources :account_activations, only: [:edit]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <nav>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar" id="icon"></span>
        <span class="icon-bar" id="icon"></span>
        <span class="icon-bar" id="icon"></span> 
      </button>
    <%= link_to root_path do %>
    <%= image_tag("logo_transparent.png",:size => '120x50', id: "logo") %> 
    <% end %>
     <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign up", signup_path, id: "navbar-li" %></li>
        <li ><%= link_to "View Orders", cart_path, id: "navbar-li" %></li>
        <% if can? :create, User %>
        <li ><%= link_to "Products", products_path, id: "navbar-li" %></li>
        <li><%= link_to "Categories", categories_path, id: "navbar-li" %></li>
        <li><%= link_to "Order report", order_items_path, id: "navbar-li" %></li>
        <% end %>
        <% if logged_in? %>
          <% if can? :create, User %>
            <li><%= link_to "Users", users_path, id: "navbar-li" %></li>
          <% end %>
        <li><%= link_to "Log out", logout_path, method: :delete, id: "navbar-li"  %></li>
        <li><%= link_to "Profile", current_user, id:"navbar-li" %></li>
          
        <% else %>
          <li><%= link_to "Log in", login_path, id: "navbar-li"%></li>
        <% end %>
      </ul>
    </div></nav>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>" id="alert"><%= message %></div>
        <% end %>
    <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>